apiVersion: apps/v1
kind: Deployment
metadata:
  name: 693project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
      - name: python-webapp
        image: <dockerhub-username>/python-webapp:latest
        ports:
        - containerPort: 5000
        